### ISSUE TITLE
elk box issue

### ISSUE THREAD

**Issue by seekdhananjay** [rajasoun/dev.box#14]
I was trying to setup the elk machine also but I'm getting the following error on ubuntu14.04:

==> elk: Booting VM...
==> elk: Waiting for machine to boot. This may take a few minutes...
    elk: SSH address: 127.0.0.1:2202
    elk: SSH username: vagrant
    elk: SSH auth method: private key
    elk: Warning: Remote connection disconnect. Retrying...
    elk: 
    elk: Vagrant insecure key detected. Vagrant will automatically replace
    elk: this with a newly generated keypair for better security.
    elk: 
    elk: Inserting generated public key within guest...
    elk: Removing insecure key from the guest if it's present...
    elk: Key inserted! Disconnecting and reconnecting using new SSH key...
    elk: Warning: Authentication failure. Retrying...
    elk: Warning: Authentication failure. Retrying...

Please have a look

**Comment by maheshbr** [comment]
Run chmod -R 755 ./.ssh/ inside the vagrant box to resolve the issue.

**Comment by seekdhananjay** [comment]
Now elk machine is also working.
