### ISSUE TITLE
Mac setup - while executing playbook, unable to proceed further.

### ISSUE THREAD

**Issue by rcramu** [rajasoun/dev.box#2]
Executed:

RCHENCHA-M-C0GS:web rchencha$ ansible -i dynamic-inventory.py -m ping all
 [WARNING]: provided hosts list is empty, only localhost is available

RCHENCHA-M-C0GS:web rchencha$ ansible -i dynamic-inventory.py -m setup all
 [WARNING]: provided hosts list is empty, only localhost is available

ansible-playbook -i dynamic-inventory.py ansible/playbooks/web_playbook.yml --vault-password-file=./secrets/.vault_pass

PLAY [all] *********************************************************************
skipping: no hosts matched

Checked the mac.setup.playbook.yml , it has indeed localhost only, Am I missing anything here ?
Pls Help.

**Comment by rajasoun** [comment]
Ramu - Can you pls. check  vagrant status. 
This might be probably due to Vagrant not being started. 
Check https://github.com/rajasoun/dev.box#provision-or-configure-the-vagrant--ansible-way

**Comment by rcramu** [comment]
Thanks, Raja, I Would check on the same & keep the issue updated.

**Comment by rcramu** [comment]
The issue is resolved, by following the steps from vagrant, Thanks.
