### ISSUE TITLE
pip install ansible=2.2 --quiet Invalid requirement: 'ansible=2.2'

### ISSUE THREAD

**Issue by Devagi** [rajasoun/dev.box#3]
I tried installing ansible using pip " pip install ansible=2.2 --quiet " and got syntax error as follows

{ ~ }  » pip install ansible=2.2 --quiet
Invalid requirement: 'ansible=2.2'
= is not a valid operator. Did you mean == ?

Update:
 pip install ansible==2.2 --quiet  this works fine

**Comment by rajasoun** [comment]
Thanks will update the ReadMe & Close the Issue
